---
title: "Classificação de Diabetes"
author: "Luan Roger Santos Santana"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
editor_options:
  markdown: null
  wrap: 72
header-includes: \PassOptionsToPackage{x11names}{xcolor}
---
```{r setup, echo=FALSE, prompt=FALSE}
library("knitr")
opts_knit$set(root.dir = "./")
library("caret")
```

# Preparing data

## Loading Data
```{r, prompt=FALSE}
data_raw <- read.csv("../data_sets/Material 03 - 9 – C - Diabetes - Dados.csv")
data_raw_new_cases <- read.csv("../data_sets/Material 03 - 9 – C - Diabetes - Dados - Novos Casos.csv")
print(head(data_raw))
print(head(data_raw_new_cases))
```

## Cleaning data
```{r, prompt=FALSE}
data <- data_raw[,!(names(data_raw) %in% c('num'))]
data_new_cases <- data_raw_new_cases[,!(names(data_raw_new_cases) %in% c('num'))]
print(head(data))
print(head(data_new_cases))
```

## Creating data partitioning

```{r, prompt=FALSE}
set.seed(1988)
ran <- sample(1:nrow(data), 0.8 * nrow(data))
training_data <- data[ran,]
test_data <- data[-ran,]
```


# Training

## Using KNN

### Creating the model
```{r, prompt=FALSE}
tuneGrid <- expand.grid(k = c(1,3,5,7,9))
set.seed(1988)
knn <- train(diabetes ~ ., data = training_data, method = "knn", tuneGrid=tuneGrid)
print(knn)
```

#### Checking the model with training data
```{r, prompt=FALSE}
prediction.knn <- predict(knn, test_data)
cf_matrix <- confusionMatrix(prediction.knn, as.factor(test_data$diabetes))
print(cf_matrix)
```
### Checking for new cases

```{r, prompt=FALSE}
prediction.knn_new_data <- predict(knn, data_new_cases)
data_new_cases$diabetes <- NULL
result <- cbind(data_new_cases, diabetes=prediction.knn_new_data)
print(result)
```

